books = [
    {
        "id": 1,
        "title": "Opekkha",
        "author": "Humayun Ahmed",
        "publisher": "Anyaprokash",
        "published_date": "1997-01-01",
        "page_count": 176,
        "language": "Bangla",
    },
    {
        "id": 2,
        "title": "Poddoja",
        "author": "Ishrat Jahan",
        "publisher": "Rodela Prokashoni",
        "published_date": "2022-01-15",
        "page_count": 320,
        "language": "Bangla",
    },
    {
        "id": 3,
        "title": "Nondito Noroke",
        "author": "Humayun Ahmed",
        "publisher": "Anyaprokash",
        "published_date": "1972-01-01",
        "page_count": 160,
        "language": "Bangla",
    },
    {
        "id": 4,
        "title": "Shonkhonil Karagar",
        "author": "Humayun Ahmed",
        "publisher": "Anyaprokash",
        "published_date": "1973-01-01",
        "page_count": 192,
        "language": "Bangla",
    },
    {
        "id": 5,
        "title": "Debi",
        "author": "Humayun Ahmed",
        "publisher": "Anannya Prokashoni",
        "published_date": "1985-01-01",
        "page_count": 112,
        "language": "Bangla",
    },
    {
        "id": 6,
        "title": "Misir Ali Omnibus",
        "author": "Humayun Ahmed",
        "publisher": "Anyaprokash",
        "published_date": "2010-01-01",
        "page_count": 520,
        "language": "Bangla",
    },
    {
        "id": 7,
        "title": "Himu",
        "author": "Humayun Ahmed",
        "publisher": "Anyaprokash",
        "published_date": "1993-01-01",
        "page_count": 144,
        "language": "Bangla",
    },
    {
        "id": 8,
        "title": "Jochona O Jononir Golpo",
        "author": "Humayun Ahmed",
        "publisher": "Anyaprokash",
        "published_date": "2004-01-01",
        "page_count": 480,
        "language": "Bangla",
    },
    {
        "id": 9,
        "title": "Pother Panchali",
        "author": "Bibhutibhushan Bandyopadhyay",
        "publisher": "Mitra O Ghosh",
        "published_date": "1929-01-01",
        "page_count": 280,
        "language": "Bangla",
    },
    {
        "id": 10,
        "title": "Shesher Kobita",
        "author": "Rabindranath Tagore",
        "publisher": "Bishwo Bharati",
        "published_date": "1929-01-01",
        "page_count": 152,
        "language": "Bangla",
    },
]
